#! /bin/sh

pgrep -x lxsession > /dev/null || lxsession &
killall picom && picom --experimental-backends || picom --experimental-backends &
$HOME/.fehbg &
# nitrogen --restore &
xsettingsd &
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#ca9ee6"
bspc config active_border_color "#eebebe"
bspc config focused_border_color "#eebebe"
bspc config presel_feedback_color "#babbf1"

bspc rule -a robloxplayerlauncher.exe state=floating
bspc rule -a robloxplayerbeta.exe desktop=^5 follow=on
